backtrace: fix NoMethodError on Ruby 2.0.*
Fixes https://github.com/airbrake/airbrake/issues/609
(NoMethodError: undefined method `cause' - Airbrake 5.5.0 - Rails)

It was my oversight. I forgot that `Exception#cause` was introduced
only in Ruby 2.1.0.