Fixes missing require for DateTime
Stops hitting this error on bare ruby usage:
```
NoMethodError: undefined method `to_datetime' for 2018-11-29 16:24:52 -0600:Time
from airbrake-ruby-2.12.0/lib/airbrake-ruby/filters/git_last_checkout_filter.rb:84'
```

The #to_datetime and #rfc3339 methods are both defined in the Date stdlib but are not included by default.

Also the test email regex didn't allow for dashes nor dots which are both relatively common.