nested_exception: fix backtrace parsing
While working on https://github.com/airbrake/airbrake/pull/479 I
stumbled upon a bug in Airbrake Ruby where the default filter couldn't
process error payload because `:backtrace` was `nil`. Returning an
empty array in case the real backtrace is missing seems to be a more
secure approach.