nested_exception: add support for Ruby 3.1 error with highlighting
Addresses https://github.com/airbrake/airbrake/issues/1230

Error highlighting is not good for our grouping. Therefore, we need to strip it
from the error message prior to reporting to Airbrake. The unstripped version of
the error is now attached to `context/error_message`.